name: HW_6
run-name: ${{ github.actor }} is testing CI GitHub Actions ğŸš€
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: Run tests and generate Allure report
        run: |
            mvn allure:clean
            mvn allure:report

      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Set job status
        run: echo "ğŸ This job's status is ${{ job.status }}."

        serve-report:
          needs: run-tests
          runs-on: ubuntu-latest

          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download Allure report artifacts
              uses: actions/download-artifact@v2
              with:
                name: allure-report
                path: allure-report

            - name: Install Allure command-line tool
              run: |
                sudo apt-add-repository -y ppa:qameta/allure
                sudo apt-get update
                sudo apt-get install allure

            - name: Serve Allure report
              run: allure serve allure-report